language: node_js
node_js:
  - 'node'
install: npm install
services:
  - postgresql
addons:
  postgresql: '9.6'

cache:
  directories:
    - 'node_modules'
env:
  global:
    - DB_ENV=test
before_script:
  - psql -c 'drop database door_test' -U postgres
  # - psql -c 'create database ldoor_test;' -U postgres
  - psql -c "ALTER ROLE postgres CONNECTION LIMIT -1"
  - npm install coveralls
script:
  - npm test
after_script:
  - jest --forceExit --coverage  --coverageReporters=text-lcov | coveralls
notifications:
  email: false
