version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
        environment:
          NODE_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          DIALECT: postgres
          DATABASE_URL: "postgres://postgres:postgres@localhost:5432/circle_test"
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
          DIALECT: postgres
          POSTGRES_PASSWORD: postgres
    
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: npm install
      - run: sudo npm install -g knex
      - run: 
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: sudo apt-get update
      - run: sudo apt install -y postgresql-client || true
      # - run: createdb population-m-s-test
      - run: 
          name: Set up DB
          command: |
            psql -h localhost -p 5432 -c 'drop database if exists circle_test;' -U postgres
            psql -h localhost -p 5432 -c 'create database circle_test;' -U postgres
            psql -h localhost -p 5432 -c "CREATE USER postgresql WITH PASSWORD 'postgres';" -U postgres

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run ci:test
