version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:12.13.1
        environment:
          NODE_ENV: testing
          DATABASE_URL: "postgresql://root@localhost/circle_test"
      - image: circleci/postgres:9.6-alpine-ram
        environment:
          POSTGRES_USER: postgres
    
    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run ci:test
