version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13.1
        environment:
          NODE_ENV: test
          DATABASE_URL: postgresql://root@localhost/ldoor_test
          POSTGRES_USER: root
          POSTGRES_DB: ldoor_test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: ldoor_test
    working_directory: ~/repo
    steps:
      - checkout

    #   # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: sudo npm install -g knex
      - run: sudo apt-get update
      - run: 
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 10m
      - run: sudo apt-get install postgresql-client-9.6 -y
      - run: psql -h localhost -p 5432 -c 'drop database if exists ldoor_test;' -U postgres
      - run: psql -U postgres -h localhost -p 5432 -c "create database ldoor_test;"
      - run: knex migrate:rollback --env test
      - run: knex migrate:latest --env test
      - run: knex seed:run --env test
      - run:
          name: Run tests
          command: |
            set -x
            docker-compose -f docker-compose.ci.yml up -d prod
            docker-compose -f docker-compose.ci.yml exec prod curl --retry 10 --retry-delay 5 -v http://127.0.0.1:8000
      # run tests
      - run: npm run ci:test
      - run:
          name: Run tests
          command: |
            set -x
            docker-compose -f docker-compose.ci.yml up -d prod
            sleep 30
            docker-compose -f docker-compose.ci.yml exec prod curl --retry 10 --retry-delay 5 -v http://127.0.0.1:8000

     